version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: